IDENTITY_SERVICE_URL: http://localhost:8001
CHAT_REALM: real-time-chat
DB_HOST: localhost
DB_PORT: 27017
DB_USER: root
DB_PASS: real-time-chat
DB_NAME: user-db
DB_AUTH_DB: admin
server:
  shutdown: graceful
  port: 8003

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDENTITY_SERVICE_URL}/realms/${CHAT_REALM}
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USER}
      password: ${DB_PASS}
      database: ${DB_NAME}
      authentication-database: ${DB_AUTH_DB}

chat:
  security:
    client-id: ${spring.application.name}
    unsecured-resources:
      - /actuator
      - /actuator/**
      - /api/users
      - /api/users/**

management:
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: info
    com:
      example:
        _: debug
        chat:
          security: debug
    io:
      micrometer: warn
      opentelemetry: warn